#!/usr/bin/env bash
# This script is displaying Best School 10 times
for i in "best School" "best School" "best School" "best School" "best School" "best School" "best School" "best School" "best School" "best School"
do
	echo "$i"
done
