#!/usr/bin/env bash
# This script prints Best School 9 times followed by Hi and then print Best School
x=1
while [ $x -le 10 ]
do
	echo "Best School"
	if [ $x == 9 ]
	then
		echo "Hi"
	fi
	x=$((x+1))
done
